DROP TABLE IF EXISTS outbox_events;
DROP TABLE IF EXISTS conversation_read_states;
DROP TRIGGER IF EXISTS messages_conversation_channel_guard ON messages;
DROP TABLE IF EXISTS messages;
DROP TRIGGER IF EXISTS conversations_identity_channel_guard ON conversations;
DROP TABLE IF EXISTS conversations;
DROP FUNCTION IF EXISTS verify_message_conversation_channel();
DROP FUNCTION IF EXISTS verify_conversation_identity_channel();
DROP SEQUENCE IF EXISTS conversation_number_seq;
DROP TABLE IF EXISTS channel_memberships;
DROP TABLE IF EXISTS contact_identities;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS channels;
DROP TYPE IF EXISTS message_status;
DROP TYPE IF EXISTS message_content_type;
DROP TYPE IF EXISTS message_actor_type;
DROP TYPE IF EXISTS message_direction;
DROP TYPE IF EXISTS conversation_priority;
DROP TYPE IF EXISTS conversation_status;
DROP TYPE IF EXISTS channel_status;
DROP TYPE IF EXISTS channel_type;
